train_dataset:
  dataset:
    name: image-folder
    args:
      root_path: ./dataset/training_hr_images
      repeat: 20
      cache: in_memory
  wrapper:
    name: sr-implicit-downsampled
    args:
      inp_size: 26  #26 or 48
      scale: 3
      augment: true
  batch_size: 16

val_dataset:
  dataset:
    name: image-folder
    args:
      root_path: ./dataset/training_hr_images
      repeat: 1
      cache: in_memory
  wrapper:
    name: sr-implicit-downsampled
    args:
      scale: 3
  batch_size: 1

data_norm:
  inp: {sub: [0.5], div: [0.5]}
  gt: {sub: [0.5], div: [0.5]}

model:
  name: model
  args:
    encoder_spec:
      name: edsr
      args:
        scale: 3

optimizer:
  name: adam
  args:
    lr: 1.e-4
epoch_max: 200
multi_step_lr:
  milestones: [100]
  gamma: 0.1

epoch_val: 1
epoch_save: 100